import { api } from "@/utils/api";
import Head from "next/head";
import { FormEvent, useState } from "react";

export default function BlogEntry() {

  const [title, setTitle] = useState("");
  const [author, setAuthor] = useState("");
  const [content, setContent] = useState("");

  const mutation = api.blogpost.insertPost.useMutation();
  
  function handlePost(e:FormEvent){
    e.preventDefault();
    mutation.mutate({author:author,title:title, content:content})
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <form>
          <h2 className="add-blog-title">Add a new blog</h2>
          <div className="form-row">
            <label htmlFor="author">Author</label>
            <input
              type="text"
              id="Author"
              name="Author"
              placeholder="Your Name"
              onChange={(e) => setAuthor(e.target.value)}
            />
          </div>
          <div className="form-row">
            <label htmlFor="title">Title</label>
            <input type="text" id="title" name="title" onChange={(e) => setTitle(e.target.value)}/>
          </div>
          <div className="form-row">
            <label htmlFor="content">Content</label>
            <textarea name="content" id="content" cols={40} onChange={(e) => setContent(e.target.value)}></textarea>
          </div>
          <div className="form-row">
            <button type="reset">Reset</button>
            <button type="submit" onClick={(e) => handlePost(e)}>Publish</button>
          </div>
        </form>
      </main>
    </>
  );
}
