import Head from "next/head";
import Navbar from "@/Components/Navbar";
import { PageDescription } from "@/Components/PageDescription";
import SortMethods from "@/Components/SortMethods";
import Bloglist from "@/Components/Bloglist";
import { api } from "@/utils/api";


export default function Home() {
  
    const {data,isLoading} = api.blogpost.getAll.useQuery();

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="main">
        <Navbar />
        <PageDescription />
        <section id="content" className="center">
          <SortMethods />
          <Bloglist />
        </section>
      </main>
    </>
  );
}
